# -*- coding: utf-8 -*-
"""AreaOfACircle2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bgDWUWjfLj8oROJyqOUwUsHQGnm-7MEY
"""

#Program to find the Area Of A Circle

r=int(input("Enter the radius of the circle"))

a=3.14*r*r

print("The Area Of The Given Circle eith the radius is", a)


#Program 2 for the file extension 

filename=input("Enter the name of your file")


if ".py" in filename:
  print("The extension of the file is : Python!")