# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nlwDhByMerxdVWj_rWC8o8xMisXm7Ejt
"""

#Python code For Fibonacci Series
num_1=0
num_2=1
sum=0
n=int(input("Enter a number upto which you want the fibonacci series to be printed : "))

for i in range(0,n):
  print(sum ,end=" ")
  num_1=num_2
  num_2=sum
  sum=num_1+num_2