# -*- coding: utf-8 -*-
"""PositiveIntegers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1olHmrnTpwtDG96v-9caRi7Tx_5Sjpngg
"""

'''Python Program to print the numbers in a range'''


n=int(input("Enter a Number of your Choice, up until which you want all the psoitive intgers to printed : "))

for i in range(1,n+1):
  print(i)