# -*- coding: utf-8 -*-
"""PositiveIntegersInAList.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1olHmrnTpwtDG96v-9caRi7Tx_5Sjpngg
"""

'''Python Program to print the numbers in a range'''

d=input("Enter the values to be entered in the list separated by commas : ")
l1=[]
l=d.split(",")

for i in l:
  if int(i)>0:
    l1.append(int(i))

print(l1)